### PR TITLE
report guest uptime to the host

### LINKED ISSUE #21: Unable to restart guest OS using vSphere
Using latest release..

First reboot works well, but when vm starts and I want to restart it again it fails with:

**"Cannot complete operation because VMware Tools is not running in this virtual machine. Failed to reset the virtual machine: Cannot execute scripts."**

Pod is running without any error log.

```
kube-system          talos-vmtoolsd-wmjjk                           1/1     Running
```

### PR DESCRIPTION
**Pull request by robinelfrink**
It appears that the host needs to know the guest's uptime information to determine if a soft reboot was succesful.

Closes #21

### CODE REVIEW

**Review by smira — APPROVED** [review]

**Comment by smira** [comment]
this PR might need `make rekres`

**Comment by robinelfrink** [comment]
> this PR might need `make rekres`

OK, a simple `make rekres` and `git commit -m 'rekres update but with better wording'` will do?

**Comment by smira** [comment]
> > this PR might need `make rekres`
> 
> OK, a simple `make rekres` and `git commit -m 'rekres update but with better wording'` will do?

squash the commits anyways

**Comment by robinelfrink** [comment]
Well, I _thought_ I got to the bottom of the reboot-only-once-problem with the change status, but I was wrong. However while trying to find the flaws in my thinking, I stumbled upon some code from the original open-vm-tools, and a couple of interesting differences between logs of vmware fusion running talos-vmtoolsd and a debian guest.

So it turns out that the host needs the guest's uptime information to know that a soft reboot has happened, and that information must be sent at a very specific place in the communication: the capabilities request.

host: "what are your capabilities?"
guest: "i've been running for 56 seconds already!"

**Review by smira — APPROVED** [review]
nice catch!

**Pull request merged**
