### PR TITLE
Add flag -use-machined for Talos system extension

### PR DESCRIPTION
**Pull request by bnason**
Flag '-use-machined' switches from using the TALOS_CONFIG_PATH and TALOS_HOST, to the Talos constants.MachineSocketPath at /system/run/machined/machine.sock. This is in support of creating a Talos system extension docker image to run talos-vmtoolsd as early in the boot process as possible.

Thanks to @flyik for the code inspiration.

### CODE REVIEW

**Comment by jonkerj** [comment]
Hi @bnason. As you might have heard, the repo changed hands, as @mologie is stepping away from using VMWare. We (Equinix) will take over from here, and we really like your approach. We will be working to get the tool compatible with recent Talos, and incorporate your suggestion/contribution, I'll be in touch.

**Comment by shkarface** [comment]
Hello @jonkerj , is there any update on this?

**Comment by robinelfrink** [comment]
Hi @bnason,

Would you please rebase on current master?

**Comment by bnason** [comment]
> Hi @bnason,
> 
> Would you please rebase on current master?

Done, though I haven't done any testing yet.

**Comment by robinelfrink** [comment]
> > Would you please rebase on current master?
> 
> Done, though I haven't done any testing yet.

Thanks. However there are still some conflicts. Please leave all definitions out of `Makefile` as they are not used, except for `SHA`:

```
# For development only.
# This Makefile is not being used by Dockerfile or GitHub actions.

SHA ?= $(shell git describe --match=none --always --abbrev=8 --dirty)

talos-vmtoolsd:
	go build -ldflags="-s -w" -trimpath -o $@ ./cmd/$@

docker-build:
	docker buildx build . --tag talos-vmtoolsd:$(SHA) --file Dockerfile

docker-build-extension:
	docker buildx build . --tag talos-vmtoolsd-system-extension:$(SHA) --file system-extension/Dockerfile

.PHONY: talos-vmtoolsd docker-build
```

**Comment by robinelfrink** [comment]
> Done, though I haven't done any testing yet.

I've tested your changes, and I got positive results:

```
$ talosctl get extensions
NODE         NAMESPACE   TYPE              ID   VERSION   NAME             VERSION
10.8.84.32   runtime     ExtensionStatus   0    1         talos-vmtoolsd   v0.5.0
```

**Comment by bnason** [comment]
> Thanks. However there are still some conflicts. Please leave all definitions out of `Makefile` as they are not used, except for `SHA`:

If the version of the Makefile in my repo, everything I think is used except maybe 2 of them. These changes help build the images with the correct tags. My plan was/is to also setup GitHub actions to automatically publish the container images for git tags and these changes would help there.

If that is not something that is wanted, I can remove the changes.


Are the go.mod and go.sum conflicts an issue? (I'm not a go dev so those files are a mystery to me lol)

**Comment by bnason** [comment]
I see why I didn't have the same merge conflicts... My upstream was still pointing to Mologies repo

**Pull request merged**
